pluginGroup = de.achimonline
pluginName = Ansible Lint
pluginDescription = <a href="https://ansible-lint.readthedocs.io/">Ansible Lint</a> integration with automatic/continuous annotation of errors, warnings, and useful information while editing.
pluginVersion = 1.11.5
pluginSinceBuild = 251

platformVersion = 2025.3

javaVersion = 21
kotlinJvmTarget = 21

kotlin.code.style = official
kotlin.stdlib.default.dependency = false
